"use strict";

// Textos da interface montados pelo JavaScript, num lugar só (regra do projeto: nada de texto
// fixo espalhado no código). O texto estático das telas fica no index.html.

const TEXTOS = {
  rotas: {
    painel: ["Operação", "Painel"],
    analise: ["Operação", "Nova análise"],
    video: ["Operação", "Vídeo ao vivo"],
    celular: ["Operação", "Câmera do celular"],
    equipamentos: ["Operação", "Equipamentos"],
    pendencias: ["Operação", "Pendências"],
    inspecoes: ["Operação", "Inspeções"],
    monitoramento: ["Operação", "Monitoramento"],
    modelos: ["Sistema", "Modelos"],
    avaliacao: ["Sistema", "Avaliação de modelos"],
    configuracoes: ["Sistema", "Configurações"],
    sobre: ["Sistema", "Sobre o Pyron"],
  },

  niveis: { normal: "Normal", atencao: "Atenção", programar: "Programar", urgente: "Urgente", imediato: "Imediato", sem_medida: "Sem medida" },
  classes: {
    ponto_quente: "Ponto quente", componente: "Componente", para_raio: "Para-raio", terminal_superior: "Terminal superior",
    isolador: "Isolador", parte_isoladora: "Parte isoladora", terminal_inferior: "Terminal inferior", bucha: "Bucha",
    conexao: "Conexão", radiador: "Radiador", tanque: "Tanque", cabo: "Cabo isolado",
  },
  aquecimento: { resistivo: "Resistivo (carga)", dieletrico: "Dielétrico (fuga)", oleo: "Óleo" },
  etapas: ["Leitura da temperatura", "Detecção", "Medição e severidade", "Laudo"],

  geral: {
    semResposta: "O Pyron não está respondendo. Se a janela principal foi fechada, abra o programa de novo.",
    erroServidor: (codigo) => `O servidor respondeu com erro ${codigo}.`,
    tentarDeNovo: "Tentar de novo",
    cancelar: "Cancelar",
    fechar: "Fechar",
    desfazer: "Desfazer",
    abrir: "Abrir",
    laudo: "Laudo",
    apagar: "Apagar",
    restaurar: "Restaurar",
    versaoDiferente: (versaoServidor, versaoTela) =>
      `O Pyron foi atualizado (interface ${versaoTela}, servidor ${versaoServidor}). Feche esta janela e abra o Pyron de novo pela área de trabalho.`,
    soImagens: "Envie imagens JPEG, PNG ou WebP.",
    naoCopiou: "Não consegui copiar. Selecione o texto e use Ctrl + C.",
    copiado: "Copiado.",
    semValor: "–",
    regioes: (n) => `${n} ${n === 1 ? "região" : "regiões"}`,
    imagens: (n) => `${n} ${n === 1 ? "imagem" : "imagens"}`,
  },

  painel: {
    configurarTitulo: "Falta pouco para emitir laudos",
    faltaResponsavel: "cadastre o responsável técnico (nome e registro)",
    faltaEmpresa: "informe o nome da empresa para o cabeçalho",
    configurarAgora: "Configurar agora",
    kpiPendencias: "Pendências vencidas",
    kpiPendenciasNota: (n) => (n === 1 ? "1 anomalia em andamento" : `${n} anomalias em andamento`),
    kpiVencidas: "Inspeções vencidas",
    kpiVencidasNota: (n) => (n === 1 ? "de 1 equipamento" : `de ${n} equipamentos`),
    proximasTitulo: "Próximas inspeções",
    proximasVencida: (d) => (d === 1 ? "vencida há 1 dia" : `vencida há ${d} dias`),
    proximasVazio: "Associe as imagens a equipamentos para o Pyron calcular a próxima inspeção de cada um.",
    verEquipamentos: "Ver equipamentos",
    erroTitulo: "Não foi possível carregar o painel",
    kpiInspecoes: "Inspeções",
    kpiInspecoesNota: (n) => (n ? `${n} vindas do monitoramento` : "análises feitas neste computador"),
    kpiCriticas: "Críticas",
    kpiCriticasNota: "urgente ou imediato",
    kpiProgramar: "Programar reparo",
    kpiProgramarNota: "reparo com data marcada",
    kpiAlertas: "Alertas pendentes",
    kpiAlertasNota: "do monitoramento",
    atencaoTitulo: "Atenção agora",
    atencaoNota: "As inspeções mais graves, da pior para a menos grave.",
    tudoCerto: "Nenhum equipamento acima dos limites",
    tudoCertoTexto: "Todas as inspeções estão em nível normal. Continue a rotina de inspeção.",
    distribuicao: "Distribuição por severidade",
    distribuicaoNota: (n) => `${n} ${n === 1 ? "inspeção" : "inspeções"} no total`,
    monitorTitulo: "Monitoramento",
    monitorLigado: "Vigiando a pasta da câmera",
    monitorDesligado: "Desligado",
    monitorErro: "Com erro",
    ultimaImagem: "Última imagem",
    ultimaVerificacao: "Última verificação",
    pasta: "Pasta",
    configurar: "Configurar",
    verAlertas: "Ver alertas",
    boasVindas: "Boas-vindas ao Pyron",
    boasVindasTexto: "Três passos para começar a manutenção preditiva com as suas imagens térmicas.",
    passo1: ["Analise um termograma", "Solte uma imagem da câmera ou use um exemplo."],
    passo2: ["Configure a empresa e o responsável", "Eles saem no cabeçalho e na assinatura dos laudos."],
    passo3: ["Ligue o monitoramento", "O Pyron vigia a pasta da câmera e avisa quando algo passar do limite."],
    analisar: "Analisar imagens",
    verExemplos: "Usar um exemplo",
    configurarEmpresa: "Configurar empresa",
    colunas: ["", "Inspeção", "Região crítica", "Severidade", ""],
  },

  analise: {
    analisando: "Analisando…",
    analisandoEtiqueta: "Processando",
    processando: ["Lendo a temperatura", "Procurando componentes", "Medindo e classificando"],
    erroTitulo: (nome) => `Não foi possível analisar ${nome}`,
    outroArquivo: "Escolher outro arquivo",
    medida: "Temperatura medida",
    estimada: "Temperatura estimada pelas cores",
    monitor: "Do monitoramento",
    detectado: (modelo) => `Detecção refeita com ${modelo}.`,
    recalculado: "Severidade recalculada com as condições informadas.",
    laudoSalvo: "Dados do laudo salvos.",
    removida: (nome) => `${nome || "Região"} removida.`,
    semRegioes: "Nenhuma região. Use Desenhar região (D) e arraste sobre a imagem.",
    camadas: { tudo: "tudo", pecas: "só peças", pontos: "só pontos quentes" },
    mostrandoCamada: (n, total, camada) => `Mostrando ${n} de ${total} regiões (${camada}).`,
    mostrarTudo: "Mostrar tudo",
    maisPertoMta: "Mais perto da MTA",
    maiorDt: "Maior ΔT entre fases",
    indicativa: " (indicativa)",
    semMedida: "sem medida",
    legendaFoto: "Foto visível (gravada junto pela câmera)",
    legendaOriginal: "Original: como a câmera gravou",
    doCelular: "Câmera do celular",
    semTemperaturaCelular: "Foto da câmera do celular: o Pyron identifica os componentes, mas a foto não traz temperatura. Para medir, use o arquivo original da câmera térmica.",
    semTemperatura: "Sem temperatura",
    semTemperaturaTitulo: "Temperatura indisponível",
    semTemperaturaComBarra: "A imagem não tem dados radiométricos e a escala da barra de cores não pôde ser lida. Os componentes foram identificados; para estimar a temperatura, informe o mínimo e o máximo escritos nas pontas da barra.",
    semTemperaturaSemBarra: "A imagem não tem dados radiométricos nem barra de cores com escala. Os componentes foram identificados, mas a temperatura só vem do JPEG original da câmera (o arquivo FLIRxxxx.jpg).",
    escalaMinima: "Mínimo da escala",
    escalaMaxima: "Máximo da escala",
    calcularTemperatura: "Calcular temperatura",
    escalaNota: "Temperatura estimada pelas cores da barra: erro típico de 0,5 °C, e o que passa do topo da escala fica no topo.",
    escalaLida: (min, max) => `Escala lida da imagem: ${min} a ${max} °C`,
    corrigirEscala: "Corrigir",
    escalaAplicada: "Escala aplicada. Temperatura estimada pelas cores.",
    etapaSemDado: "sem dado",
    laudoSemTemperatura: "Sem temperatura medida, não há laudo termográfico. Informe a escala na aba Resultado ou envie o JPEG radiométrico da câmera.",
    dicaRegiao: "Arraste para medir uma região · Esc cancela",
    dicaPonto: "Clique para medir um ponto · Esc volta à seleção",
    dicaLinha: "Arraste para traçar uma linha e ver o perfil · Esc volta à seleção",
    medVazio: "Nenhum ponto ou linha. Use Ponto (P) para ler a temperatura de um pixel e Linha (L) para o perfil ao longo de um trecho.",
    medRemover: "Remover",
    medLinha: (max, min, med) => `máx ${max} · mín ${min} · média ${med} °C`,
    perfilTitulo: "Perfil de temperatura ao longo da linha",
    escalaInvalida: "Escala inválida: o máximo precisa ser maior que o mínimo.",
    exportarImagem: "Imagem com as regiões",
    exportarImagemNota: "PNG na paleta e escala da tela",
    exportarCsv: "Temperaturas de todos os pixels",
    exportarCsvNota: "CSV que abre no Excel",
    exportarLaudo: "Laudo em PDF",
    exportarLaudoNota: "com o responsável técnico",
    parametrosAplicados: (e) => `Temperaturas recalculadas com emissividade ${e}.`,
    parametrosRestaurados: "Voltou aos parâmetros gravados pela câmera.",
    ajustados: (e) => `Parâmetros ajustados · ε ${e}`,
    ajustadosTitulo: "Emissividade, distância ou temperaturas trocadas depois da captura; veja na aba Condições.",
    daImagem: "da imagem",
    regiaoNova: (n) => `Região ${n}`,
    remover: (nome) => `Remover ${nome}`,
    removerTitulo: "Remover (Delete)",
    nomeRegiao: "Nome da região",
    classe: "Classe",
    tituloBarraMta: (tp, mta, fonte) => `${tp} °C de ${mta} °C admissíveis (${fonte})`,
    tituloBarraEscala: "Temperatura máxima na escala da imagem",
    criterio: (lista) => ` Critério: ${lista}.`,
    indicativaDica: " Classificação indicativa: informe ambiente e carga ou compare fases.",
    plenaCarga: (tp, mta) => `≈ ${tp} °C a plena carga (${mta})`,
    semCarga: (mta) => `${mta}, sem carga informada`,
    semProjecao: (mta) => `${mta}, sem projeção`,
    dtFases: (dt) => `ΔT fases ${dt}`,
    atingeMtaCarga: (pct) => `atinge a MTA com ${pct}% da carga`,
    atingeMtaCorrente: (x) => `atinge a MTA com ${x}× a corrente atual`,
    compararFases: "compare com as outras fases",
    confianca: (pct) => `confiança ${pct}%`,
    pctMta: (pct) => `${pct}% da MTA`,
    noEntorno: (dt) => `+${dt} °C no entorno`,
    // componentes × pontos quentes
    pqTitulo: "Ponto mais quente",
    pqTituloPecas: "Ponto mais quente nas peças",
    pqFora: (nome, t) => `Mais quente fora das peças: ${nome}, ${t}`,
    pqEm: (nome) => `em ${nome}`,
    pqForaDePeca: "fora das peças identificadas",
    pqDentroDe: (nomes) => `(dentro de ${nomes})`,
    pqVer: "Ver na imagem",
    pqImagem: (t, onde) => `Ponto mais quente: ${t}${onde ? ` em ${onde}` : ""}`,
    naPeca: (nome) => `em ${nome}`,
    foraDePeca: "fora das peças",
    compTitulo: "Comparação entre componentes",
    compNota: "Temperatura máxima de cada peça e a diferença para as peças iguais (a referência do critério). Clique numa linha para ver a peça na imagem.",
    compAmplitude: (dt) => `${dt} °C entre a mais quente e a mais fria`,
    compSozinho: "sem peça igual para comparar",
    compColunas: ["Peça", "Tmáx", "ΔT"],
    meta: {
      origem: "Origem", camera: "Câmera", emissividade: "Emissividade", distancia: "Distância", refletida: "T. refletida",
      umidade: "Umidade", sensor: "Sensor", escala: "Escala lida", medida: "medida", estimada: "estimada",
    },
    loteTitulo: (n) => `Analisando ${n} imagens`,
    loteFila: "na fila",
    loteAndando: "analisando…",
    loteProgresso: (i, n) => `${i} de ${n} processadas`,
    loteFim: (ok, n) => `${ok} de ${n} analisadas.`,
    verInspecoes: "Ver inspeções",
  },

  inspecoes: {
    erroTitulo: "Não foi possível carregar as inspeções",
    total: "Inspeções",
    criticas: "Críticas",
    programar: "Programar reparo",
    atencao: "Atenção",
    normais: "Normais",
    vazioTitulo: "Nenhuma inspeção ainda",
    vazioTexto: "Analise um termograma e ele aparece nesta lista, com severidade, regiões e laudo.",
    nadaTitulo: "Nada encontrado",
    nadaTexto: "Nenhuma inspeção com esse filtro ou busca. Limpe a busca ou escolha outra severidade.",
    limpar: "Limpar filtros",
    colunas: ["", "Inspeção", "Local", "Região crítica", "Máx. da cena", "Severidade", ""],
    laudoTitulo: "Laudo em PDF",
    marcar: (arquivo) => `Selecionar ${arquivo} para o relatório`,
    marcarTodas: "Selecionar todas as inspeções da lista",
    selecionadas: (n) => `${n} ${n === 1 ? "inspeção selecionada" : "inspeções selecionadas"}`,
    gerarRelatorio: (n) => (n === 1 ? "Gerar laudo" : `Gerar relatório com ${n}`),
    limparSelecao: "Limpar seleção",
    semEquipamento: "Sem equipamento",
    apagarTitulo: "Apagar inspeção?",
    apagarTexto: (arquivo) => `${arquivo} e suas regiões serão apagadas deste computador. Não dá para desfazer.`,
    apagada: "Inspeção apagada.",
    rotuloApagar: (arquivo) => `Apagar ${arquivo}`,
    monitor: "Monitor",
  },

  monitor: {
    erroTitulo: "Não foi possível carregar o monitoramento",
    estado: "Estado",
    vigiando: "Vigiando",
    desligado: "Desligado",
    comErro: "Com erro",
    pasta: "Pasta",
    semPasta: "não definida",
    ultimaVerificacao: "Última verificação",
    ultimaImagem: (arquivo) => `última imagem: ${arquivo}`,
    analisadas: "Analisadas nesta sessão",
    alertasPendentes: (n) => `${n} ${n === 1 ? "alerta pendente" : "alertas pendentes"}`,
    ligar: "Ligar monitoramento",
    desligar: "Desligar monitoramento",
    ligado: "Monitoramento ligado. Só as imagens que chegarem a partir de agora serão analisadas.",
    desligadoAviso: "Monitoramento desligado.",
    salvo: "Configuração do monitoramento salva.",
    verificado: (n) => (n ? `${n} ${n === 1 ? "imagem nova analisada" : "imagens novas analisadas"}.` : "Nenhuma imagem nova na pasta."),
    nome: "Nome",
    telefone: "WhatsApp",
    telefoneExemplo: "+55 83 99999-0000",
    removerDestinatario: (nome) => `Remover ${nome || "responsável"}`,
    semDestinatarios: "Ninguém cadastrado. Adicione pelo menos um responsável para receber os avisos.",
    previaVazia: "A prévia aparece depois da primeira inspeção salva.",
    previaRodape: (arquivo) => `Exemplo com a inspeção mais grave: ${arquivo}`,
    alertasVazioTitulo: "Nenhum alerta ainda",
    alertasVazioTexto: "Quando uma imagem da pasta atingir a severidade mínima, o alerta aparece aqui e no sino do topo.",
    colunas: ["Quando", "Imagem", "Severidade", "Resumo", "Situação", ""],
    status: { pendente: "Pendente", enviado: "Enviado", resolvido: "Resolvido" },
    whatsapp: "WhatsApp",
    resolver: "Resolver",
    resolvido: "Alerta marcado como resolvido.",
    dialogoTitulo: "Enviar pelo WhatsApp",
    dialogoTexto: "Cada botão abre o WhatsApp com a mensagem pronta. Confira e toque em enviar.",
    dialogoSemDestinatarios: "Nenhum responsável cadastrado. Cadastre em Monitoramento › Responsáveis, ou copie a mensagem.",
    abrirWhatsapp: "Abrir WhatsApp",
    copiarMensagem: "Copiar mensagem",
    novoAlerta: (sev) => `Novo alerta do monitoramento: ${sev}.`,
    verAlerta: "Ver",
    chipLigado: "Monitoramento ativo",
    chipDesligado: "Monitoramento desligado",
    chipErro: "Monitoramento com erro",
  },

  modelos: {
    erroTitulo: "Não foi possível carregar os modelos",
    emUso: "Em uso",
    usar: "Usar este modelo",
    passaASer: (nome) => `${nome} passa a ser usado nas próximas análises.`,
    regra: "Regra",
    ia: "IA treinada",
    combinado: "IA + regra",
    regraSemIa: "Regra, sem IA",
    embutido: "Embutido no programa",
    instaladoEm: "Instalado em modelos",
    combinadoNota: "Modelo instalado + regra embutida",
    versao: (arq, v) => `${arq} · versão ${v}`,
    treino: "Treino",
    desempenho: "Desempenho",
    limitacoes: "Limitações",
    instalado: (id) => `Modelo ${id} instalado. Clique em "Usar este modelo" para ativar.`,
  },

  avaliacao: {
    erroTitulo: "Não foi possível carregar a avaliação",
    vazioTitulo: "Nenhuma avaliação importada",
    vazioTexto: "Rode o caderno Treino_para_raios_Colab.ipynb no Google Colab e importe aqui o resultados_comparacao.zip (ou o pacote do modelo, que traz os resultados junto). A comparação aparece com gráficos, tabelas e as fotos de teste.",
    importar: "Importar do Colab",
    importando: "Importando os resultados…",
    importou: (partes) => `Importado: ${partes.join(" e ")}.`,
    parteAvaliacao: "a comparação dos modelos",
    parteModelo: (id) => `o modelo ${id}`,
    opcao: (m) => `${m.importado_em.replace("T", " ").slice(0, 16)} · ${m.modelos.length} modelos · melhor ${m.melhor}`,
    apagar: "Apagar esta avaliação",
    apagarTitulo: "Apagar esta avaliação?",
    apagarTexto: "Os gráficos e as figuras desta comparação saem do Pyron. O modelo instalado, se houver, continua em Modelos.",
    apagada: "Avaliação apagada.",
    // resumo
    melhor: "Melhor no teste",
    melhorNota: (mapa) => `mAP50 ${mapa}`,
    revocacao: "Peças encontradas",
    revocacaoNota: (acertos, total) => `${acertos} de ${total} peças no teste`,
    perdidas: "Peças que escaparam",
    perdidasNota: (modelo) => `no ${modelo}`,
    fotos: "Fotos",
    fotosNota: (t, v) => `${t} de treino · ${v} de validação`,
    fotosTeste: (n) => `${n} de teste`,
    empate: (a, b, dif) => `${a} e ${b} ficaram empatados: a diferença é de ${dif} ${dif === 1 ? "peça" : "peças"} no teste, dentro do que muda de uma divisão de fotos para outra.`,
    vantagem: (a, b, dif) => `${a} achou ${dif} peças a mais que ${b} no teste.`,
    pontoFraco: (classe, ap) => `Ponto fraco comum: ${classe} (AP50 médio ${ap}). Quando todos os modelos erram a mesma peça, a causa costuma estar nos dados: peça pequena, encoberta ou rotulada de jeitos diferentes.`,
    // cartões
    comparacao: "Comparação no teste",
    comparacaoNota: "Fotos que nenhum modelo viu no treino. Maior é melhor em todas as barras.",
    metricas: ["mAP50", "mAP50-95", "Precisão", "Revocação", "F1"],
    colunas: ["Modelo", "mAP50", "mAP50-95", "Precisão", "Revocação", "F1", "IoU médio", "Acertos", "Falsos", "Perdidos", "Limiar", "ms por foto"],
    colunasTemperatura: ["Erro Tmáx (°C)", "Erro Tmáx p90 (°C)"],
    tmax: "Erro da temperatura máxima",
    tmaxNota: (p90, n) => `mediana em ${n} peças achadas · 90% até ${p90} °C`,
    tmaxExplica: "Diferença entre a Tmáx medida na caixa do modelo e na caixa rotulada, na matriz radiométrica da câmera. É o que decide a severidade no Pyron.",
    porClasse: "Por componente",
    porClasseNota: "AP50: acerto da peça. AP50-95: caixa justa. Revocação: das peças que existem, quantas o modelo achou.",
    colunasClasse: ["AP50", "AP50-95", "Revocação"],
    componente: "Componente",
    curvas: "Como cada modelo aprendeu",
    curvasNota: "Perda (loss) caindo nas duas linhas: está aprendendo. Treino caindo e validação subindo: está decorando. A linha pontilhada marca a melhor época, que é a que fica no modelo.",
    perda: (m) => `${m}: perda`,
    treino: "treino",
    validacao: "validação",
    mapaValidacao: "mAP50 na validação",
    epoca: "época",
    semCurvas: "Esta avaliação não trouxe o histórico de treino.",
    pecasPerdidas: "Peças perdidas e o limiar de confiança",
    pecasPerdidasNota: "Onde o melhor modelo mais erra, e o que muda se o limiar de confiança for mais baixo (mais peças encontradas, mais caixas falsas).",
    figuras: "Fotos de teste marcadas",
    figurasNota: "Verde: acerto. Vermelho: caixa falsa. Amarelo tracejado: peça rotulada que o modelo não achou. Clique para ver em tamanho real.",
    figura: {
      "curvas.png": "Curvas de treino",
      "metricas.png": "Métricas no teste",
      "piores_fotos.png": "As fotos mais difíceis",
      "pecas_perdidas.png": "Peças perdidas, de perto",
    },
    figuraTeste: (nome) => `Fotos de teste ${nome.replace(/^teste_|\.png$/g, "").replace("_a_", " a ")}`,
    dados: "Dados e configuração",
    linhasDados: {
      importado: "Importado em",
      arquivo: "Arquivo",
      gpu: "Treinado em",
      divisao: "Divisão das fotos",
      classes: "Classes",
      formato: "Anotações",
      limiares: "Limiar de confiança",
    },
    divisao: (f) => `${f.treino ?? "–"} treino · ${f.validacao ?? "–"} validação · ${f.teste ?? "–"} teste`,
    modeloInstalado: "Modelo instalado no Pyron",
    modeloInstaladoNota: "O pacote trouxe o modelo pronto. Ele já aparece em Modelos.",
    emUso: "Em uso nas análises",
    usarModelo: "Usar este modelo nas análises",
    irModelos: "Ver em Modelos",
  },

  treino: {
    ambienteOk: (msg) => msg,
    ambienteBloqueado: "Treino bloqueado neste computador",
    ambienteVerificando: "Verificando o PyTorch…",
    soltar: "Solte aqui as anotações do CVAT",
    soltarNota: "O .zip exportado ou os .json da pasta annotations (selecione os três juntos). COCO 1.0, com caixas ou polígonos.",
    escolher: "Escolher arquivo",
    analisando: "Lendo os rótulos e conferindo cada imagem…",
    erroAnalise: "Não foi possível ler os rótulos",
    imagensProntas: "Imagens prontas",
    deTotal: (n) => `de ${n} rotuladas`,
    rotulos: "Rótulos",
    tipos: (t) => Object.entries(t).filter(([, v]) => v).map(([k, v]) => `${v} ${{ caixa: "caixa", poligono: "polígono", mascara: "máscara" }[k]}${v === 1 ? "" : "s"}`).join(" · "),
    classes: "Classes",
    sessoes: "Sessões de fotos",
    divisaoCvat: (s) => `Divisão do CVAT: ${Object.entries(s).map(([k, v]) => `${{ treino: "treino", validacao: "validação", teste: "teste" }[k]} ${v}`).join(", ")}`,
    colunasClasses: ["Classe", "Rótulos", "Imagens"],
    nome: "Nome do modelo",
    id: "Identificador",
    idAjuda: "Nome da pasta do modelo: letras minúsculas, números e hífen.",
    epocas: "Épocas",
    epocasAjuda: "Quantas vezes a rede passa por todas as imagens. 60 é um bom começo.",
    divisao: "Separação treino / teste",
    porSessao: "Por sessão (recomendado)",
    doCvat: "A do CVAT",
    divisaoAjuda: "Por sessão, fotos quase iguais do mesmo momento não ficam dos dois lados: a nota do teste fica honesta.",
    trocar: "Trocar arquivo",
    pacote: "Baixar pacote para treinar fora",
    pacoteNota: "Google Colab, supercomputador ou outro PC com GPU. Depois, Instalar modelo treinado.",
    comecar: "Começar treino",
    naoPronto: "Poucas imagens utilizáveis para treinar (mínimo 8).",
    iniciado: (nome) => `Treino de ${nome} começou. Dá para acompanhar aqui ou fechar a janela: ele continua.`,
    pacoteBaixado: "Pacote baixado. Abra o LEIA-ME dentro dele para os passos do Colab.",
    etapas: { iniciando: "Iniciando", lendo: "Lendo rótulos", treinando: "Treinando", avaliando: "Avaliando", exportando: "Exportando", pronto: "Pronto", erro: "Erro", cancelado: "Cancelado", interrompido: "Interrompido" },
    classeEtapa: { pronto: "disponivel", erro: "erro", cancelado: "estimada", interrompido: "estimada" },
    restante: (r) => (r ? ` · faltam ~${r}` : ""),
    perda: (ultima, primeira) => `perda ${ultima} (começou em ${primeira})`,
    cancelar: "Cancelar",
    cancelarTitulo: "Cancelar o treino?",
    cancelarTexto: "O treino para agora e nada é instalado. Os rótulos continuam guardados.",
    cancelado: "Treino cancelado.",
    usar: "Usar este modelo",
    verRegistro: "Ver registro do treino",
    previsoes: "Previsões nas imagens de teste (tracejado verde: seu rótulo; laranja: o modelo)",
    metricas: { mAP50: "mAP50 (acerto das caixas)", revocacao: "Encontrados", erro: "Erro da Tmáx (mediana)", erro90: "Erro da Tmáx (90% até)" },
    porClasse: ["Classe", "AP50", "Encontrados"],
    divisaoUsada: (d, tr, te) => `${tr} imagens de treino, ${te} de teste · ${d}`,
    chip: (t) => `Treinando ${t.percentual}%`,
  },

  laudo: {
    titulo: "Gerar laudo",
    tituloVarios: (n) => `Relatório com ${n} imagens`,
    ordem: "As imagens entram na ordem da lista de inspeções, uma por página, com um resumo no início.",
    responsavel: "Responsável técnico",
    art: "ART nº",
    artOpcional: "opcional",
    gerar: "Gerar PDF",
    gerando: "Gerando o relatório…",
    pronto: "Laudo gerado.",
    prontoVarios: (n) => `Relatório com ${n} imagens gerado.`,
    semResponsavelTitulo: "Cadastre o responsável técnico",
    semResponsavelTexto: "O laudo só sai com um responsável do cadastro, para o nome e o registro nunca saírem digitados errado. Cadastre em Configurações › Empresa e responsáveis.",
    cadastrar: "Cadastrar agora",
    selecione: "Escolha o responsável",
  },

  comparar: {
    titulo: "Inspeção anterior deste equipamento",
    anterior: (d) => `${d} `,
    delta: (d, antes, agora) => `${d} °C na máxima (${antes} → ${agora} °C)`,
    ladoALado: "Lado a lado",
    abrir: "Abrir",
    ladoALadoTitulo: (equip) => `${equip}: antes e agora`,
    antes: "Antes",
    agora: "Agora",
    maxima: "Máxima",
    anteriorTitulo: "Inspeção anterior do equipamento",
    seguinteTitulo: "Próxima inspeção do equipamento",
    posicao: (i, n) => `${i} de ${n}`,
  },

  busca: {
    grupoTelas: "Telas",
    grupoAcoes: "Ações",
    grupoEquipamentos: "Equipamentos",
    grupoInspecoes: "Inspeções",
    nada: "Nada encontrado. Tente o nome do arquivo, do equipamento ou da instalação.",
    telas: {
      painel: ["Painel", "painel"], analise: ["Nova análise", "analise"], video: ["Vídeo ao vivo", "video"],
      inspecoes: ["Inspeções", "inspecoes"], equipamentos: ["Equipamentos", "ativos"], pendencias: ["Pendências", "chave"],
      monitoramento: ["Monitoramento", "camera"], modelos: ["Modelos", "modelos"], avaliacao: ["Avaliação de modelos", "grafico"],
      configuracoes: ["Configurações", "config"], sobre: ["Sobre o Pyron", "info"],
    },
    acaoAnalisar: "Analisar imagens…",
    acaoVideo: "Analisar um vídeo da câmera",
    acaoPlanilha: "Exportar planilha de inspeções (Excel)",
    acaoTema: "Alternar tema claro ou escuro",
    acaoAtalhos: "Atalhos de teclado",
  },

  atalhos: {
    titulo: "Atalhos de teclado",
    grupos: [
      ["Em qualquer tela", [["Ctrl+K", "Busca rápida"], ["Ctrl+O", "Analisar imagens"], ["?", "Esta lista"]]],
      ["Na análise", [["S", "Selecionar"], ["D", "Desenhar região"], ["P", "Medir um ponto"], ["L", "Perfil ao longo de uma linha"],
        ["R", "Rótulos sobre as caixas"], ["Delete", "Remover a região selecionada"], ["Esc", "Cancelar e voltar à seleção"]]],
      ["No vídeo", [["Espaço", "Reproduzir ou pausar"], ["←", "Quadro anterior"], ["→", "Próximo quadro"], ["R", "Rótulos"]]],
    ],
  },

  pend: {
    erroTitulo: "Não consegui carregar as pendências",
    vazioTitulo: "Nenhuma anomalia para acompanhar",
    vazioTexto: "Quando uma inspeção sai fora do normal, ela aparece aqui com o prazo de correção pela severidade.",
    nadaTitulo: "Nenhuma pendência nesse filtro",
    nadaTexto: "Troque o filtro ou a busca.",
    kAndamento: "Em andamento",
    kVencidas: "Prazo vencido",
    kReinspecao: "Aguardando reinspeção",
    kConcluidas: "Concluídas",
    status: { aberta: "Aberta", programada: "Programada", corrigida: "Corrigida", verificada: "Verificada", descartada: "Descartada" },
    colSeveridade: "Severidade",
    colEquipamento: "Equipamento e região",
    colDetectada: "Detectada",
    colPrazo: "Prazo",
    colSituacao: "Situação",
    colOs: "OS",
    ver: "Ver",
    abrirInspecao: "Abrir a inspeção",
    atualizar: "Atualizar",
    vencidaHa: (d) => (d === 1 ? "vencido há 1 dia" : `vencido há ${d} dias`),
    faltam: (d) => (d <= 0 ? "vence hoje" : d === 1 ? "falta 1 dia" : `faltam ${d} dias`),
    reinspecaoNormal: (d) => `normal em ${d}`,
    reinspecaoTexto: (d) => `A inspeção de ${d} do mesmo equipamento saiu normal: se for depois do reparo, marque como verificada.`,
    dialogoTitulo: (equip) => `Acompanhamento · ${equip}`,
    detectadaEm: (d) => `detectada em ${d}`,
    situacao: "Situação",
    prazo: "Prazo para corrigir",
    os: "Ordem de serviço",
    osExemplo: "OS 2026-0142",
    osCurta: (os) => (/^os\b/i.test(os) ? os : `OS ${os}`),
    responsavel: "Responsável pela correção",
    responsavelExemplo: "Equipe de manutenção",
    nota: "Nota (vai para o histórico)",
    notaExemplo: "Conector reapertado e limpo; reinspecionar com carga.",
    historico: (n) => (n === 1 ? "Histórico (1 registro)" : `Histórico (${n} registros)`),
    salvar: "Salvar",
    salva: (s) => `Pendência atualizada: ${s.toLowerCase()}.`,
    cartaoTitulo: "Acompanhamento da anomalia",
  },

  equip: {
    erroTitulo: "Não consegui carregar os equipamentos",
    vazioTitulo: "Nenhum equipamento ainda",
    vazioTexto: "Diga a que equipamento cada imagem pertence (instalação e equipamento) e o Pyron monta o histórico, a tendência da temperatura e a data da próxima inspeção.",
    vazioAcao: "Definir em Inspeções",
    nadaTitulo: "Nenhum equipamento nesse filtro",
    nadaTexto: "Troque o filtro ou a busca.",
    kTotal: "Equipamentos",
    kAnomalia: "Com anomalia",
    kVencida: "Inspeção vencida",
    kEsquentando: "Esquentando",
    kEsquentandoNota: "mais de 0,5 °C por mês",
    semInstalacao: "Sem instalação informada",
    semEquipTitulo: (n) => (n === 1 ? "1 inspeção sem equipamento" : `${n} inspeções sem equipamento`),
    semEquipTexto: "Elas não entram no histórico. Em Inspeções, marque as imagens e use Definir equipamento.",
    inspecoes: (n) => (n === 1 ? "1 inspeção" : `${n} inspeções`),
    ultima: (d) => `última em ${d}`,
    desde: (d) => `desde ${d}`,
    proxima: (d) => `Próxima inspeção ${d}`,
    vencidaHa: (dias) => (dias === 1 ? "Inspeção vencida há 1 dia" : `Inspeção vencida há ${dias} dias`),
    emDias: (dias) => (dias <= 0 ? "hoje" : dias === 1 ? "amanhã" : `em ${dias} dias`),
    tendencia: (v) => `${v} °C/mês`,
    semTendencia: "sem tendência ainda",
    semTendenciaDica: "A tendência precisa de 3 inspeções em datas diferentes, com ao menos um mês entre a primeira e a última.",
    tendenciaTitulo: (r2, n) => `Ajuste por mínimos quadrados de ${n} inspeções (R² ${r2}).`,
    tendenciaInstavel: " Os pontos variam muito: confira carga e condições de cada inspeção.",
    estimativaMta: (d) => `Se a tendência continuar, chega à MTA por volta de ${d}.`,
    estimativaFraca: " Estimativa fraca: poucos pontos ou muita variação.",
    voltar: "Voltar para os equipamentos",
    relatorio: "Relatório do equipamento",
    adicionar: "Adicionar imagens",
    adicionarTitulo: "Analisa imagens novas já como inspeções deste equipamento",
    estadoAtual: "Estado atual",
    tmaxUltima: "Máxima na última",
    tendenciaRotulo: "Tendência",
    proximaRotulo: "Próxima inspeção",
    prazo: (dias) => `prazo de ${dias === 365 ? "1 ano" : dias === 1 ? "1 dia" : `${dias} dias`} pela severidade`,
    graficoTitulo: "Temperatura máxima ao longo das inspeções",
    graficoDica: "Cada ponto é uma inspeção, na cor da severidade; clique para abrir.",
    graficoPlenaTitulo: "Elevação sobre o ambiente, projetada para plena carga",
    tendenciaPlenaRotulo: "Tendência a plena carga",
    plenaNota: "ΔT sobre o ambiente × (100 / carga)², como na NBR 15866: compara inspeções feitas com cargas diferentes.",
    serieRotulo: "Série do gráfico",
    serieMedida: "Temperatura medida",
    serieplena: "A plena carga",
    graficoPecasTitulo: "Máxima de cada tipo de peça",
    componentes: "Peças",
    colPeca: "Peça",
    colUltima: "Última máxima",
    colDt: "ΔT",
    colTendencia: "Tendência",
    colEstado: "Estado",
    historico: "Histórico de inspeções",
    abrir: "Abrir",
    definir: "Definir equipamento",
    definirTitulo: (n) => (n === 1 ? "Equipamento da inspeção" : `Equipamento de ${n} inspeções`),
    definirTexto: "As imagens passam a contar no histórico deste equipamento. Use sempre o mesmo nome para o mesmo equipamento; as sugestões ajudam.",
    instalacao: "Instalação",
    equipamento: "Equipamento",
    salvar: "Salvar",
    obrigatorio: "Informe o equipamento.",
    definido: (n, equip) => (n === 1 ? `Inspeção associada a ${equip}.` : `${n} inspeções associadas a ${equip}.`),
    verEquipamento: "Ver equipamento",
    chip: (equip) => equip,
    chipTitulo: "Histórico e tendência deste equipamento",
  },

  video: {
    modoAoVivo: "O vídeo corre no relógio, como a câmera: enquanto o detector trabalha, os quadros que passam se perdem. Mostra o que o sistema acompanharia de verdade neste computador.",
    modoIntervalo: "Analisa um quadro a cada intervalo do vídeo, sem perder nenhum. Leva o tempo que precisar.",
    enviando: (pct) => `Enviando o vídeo… ${pct}%`,
    enviado: "Vídeo recebido. A análise começou.",
    soVideos: "Envie um vídeo MP4, AVI, MOV, MKV, M4V, WMV ou WEBM.",
    vazioTitulo: "Nenhum vídeo analisado",
    vazioTexto: "Envie a gravação da tela da câmera para ver como o detector se comporta quadro a quadro, como se estivesse ao vivo.",
    erroTitulo: "Não consegui carregar os vídeos",
    total: (n) => (n === 1 ? "1 vídeo" : `${n} vídeos`),
    status: { na_fila: "Na fila", processando: "Analisando", concluido: "Concluído", cancelado: "Parado", interrompido: "Interrompido", erro: "Falhou" },
    nQuadros: (n) => (n === 1 ? "1 quadro" : `${n} quadros`),
    apagarRotulo: (nome) => `Apagar ${nome}`,
    apagarTitulo: "Apagar o vídeo?",
    apagarTexto: (nome) => `${nome} e os quadros analisados saem deste computador. As inspeções salvas a partir dele continuam.`,
    apagado: "Vídeo apagado.",
    parando: "Parando a análise…",
    parado: "Análise parada. O que já foi analisado continua disponível.",
    concluido: "Análise do vídeo concluída.",
    aoVivo: "AO VIVO",
    reproducao: "Reprodução",
    pausado: "Pausado",
    preparando: "Preparando o leitor da escala e o detector…",
    naFila: "Na fila: começa quando o vídeo anterior terminar.",
    semEscalaCurta: "sem escala",
    kQuadros: "Quadros analisados",
    kQuadrosDe: (total) => `de ${total} do vídeo`,
    kRitmo: "Ritmo real",
    kRitmoNota: (fps) => `quadros por segundo; o vídeo tem ${fps}`,
    kLatencia: "Tempo por quadro",
    kLatenciaNota: (p95) => `95% abaixo de ${p95} ms`,
    kMaxima: "Máxima no vídeo",
    graficoTitulo: "Máxima da cena ao longo do vídeo",
    graficoVazio: "Sem temperatura: a escala não foi lida em nenhum quadro.",
    graficoEspera: "A curva aparece com os primeiros quadros.",
    graficoDica: "Clique no gráfico para ir àquele instante.",
    neste: "Neste quadro",
    instante: "Instante",
    quadroN: (i) => `quadro ${i} do vídeo`,
    escala: "Escala",
    fontes: { lida: "lida agora", repetida: "mesma já lida", informada: "informada", anterior: "a última lida", sem_escala: "não encontrada" },
    tempo: "Tempo de análise",
    etapas: (t, d, m) => `temperatura ${t} · detecção ${d} · medição ${m} ms`,
    preparo: (ms) => `${ms} ms, com a preparação (fica fora da média)`,
    perdidos: "Perdidos antes",
    pulados: (n) => (n === 1 ? "1 quadro" : `${n} quadros`),
    semRegioes: "Nada detectado neste quadro.",
    erroQuadro: "Este quadro falhou na análise; os seguintes continuaram.",
    eventos: (n) => (n ? `Momentos com anomalia (${n})` : "Momentos com anomalia"),
    semEventos: "Nenhuma anomalia nos quadros analisados.",
    eventoResumo: (n, t) => `${n === 1 ? "1 quadro" : `${n} quadros`} · máx. ${t}`,
    salvo: (nome) => `Quadro salvo como inspeção: ${nome}.`,
    abrir: "Abrir",
    tocar: "Reproduzir",
    pausar: "Pausar",
    modoVivo: (v) => `Ao vivo ${v}×`,
    modoIntervalo: (s) => `Um quadro a cada ${s} s`,
    escalaFixa: (a, b) => `Escala fixa ${a} a ${b} °C`,
    escalaLida: "Escala lida da imagem",
    duracao: (d, fps) => `${d} · ${fps} quadros/s`,
  },

  config: {
    erroTitulo: "Não foi possível carregar as configurações",
    usoDados: (total, n, videos) => `${total} · ${n === 1 ? "1 inspeção" : `${n} inspeções`}${videos ? ` (vídeos: ${videos})` : ""}`,
    restaurarTitulo: "Restaurar este backup?",
    restaurarTexto: (nome) => `As inspeções, equipamentos, pendências e configurações atuais serão trocados pelos de ${nome}. Antes, uma cópia do que está aqui hoje fica guardada na pasta de dados, em backups.`,
    restaurarAcao: "Restaurar",
    restaurado: (n) => `Backup restaurado: ${n === 1 ? "1 inspeção" : `${n} inspeções`}. Recarregando…`,
    logoSalvo: "Logotipo salvo. Os próximos laudos saem com ele no cabeçalho.",
    logoRemovido: "Logotipo removido.",
    logoAlt: "Logotipo da empresa",
    logoEnviar: "Enviar logotipo",
    logoTrocar: "Trocar logotipo",
    empresaSalva: "Empresa e responsáveis salvos. Os próximos laudos saem com esses dados.",
    respNome: "Nome",
    respFuncao: "Função",
    respFuncaoExemplo: "Engenheiro eletricista",
    respRegistro: "Registro profissional",
    respRegistroExemplo: "CREA-PB 000000",
    respPadrao: "Padrão",
    respPadraoTitulo: "Vem escolhido em cada nova análise",
    respRemover: (nome) => `Remover ${nome || "responsável"}`,
    criterioSalvo: "Critério salvo. As inspeções foram recalculadas.",
    criterioModelo: (nome) => `Modelo ${nome} carregado no formulário. Salve para aplicar.`,
    criterioPersonalizado: "Critério personalizado em uso. As inspeções salvas são recalculadas quando ele muda.",
    criterioPadrao: "Em uso: modelo brasileiro (NBR 15866). Confira os limites com o seu termografista responsável.",
    aPartirDe: " a partir de",
    naoUsar: "não usar",
    limiteRotulo: (nivel, unidade) => `${nivel}, limite em ${unidade}`,
    restaurarCriterioTitulo: "Restaurar o critério padrão?",
    restaurarCriterioTexto: "Os limites voltam ao modelo brasileiro (NBR 15866) e as inspeções são recalculadas.",
    criterioRestaurado: "Critério padrão restaurado.",
    bibliotecaSalva: "Biblioteca salva. As inspeções foram recalculadas.",
    restaurarBibliotecaTitulo: "Restaurar a biblioteca padrão?",
    restaurarBibliotecaTexto: "As MTAs voltam aos valores das normas e da prática brasileira, e as inspeções são recalculadas.",
    bibliotecaRestaurada: "Biblioteca padrão restaurada.",
    naoSeAplica: "não se aplica",
    mtaRotulo: (nome) => `MTA de ${nome}`,
    fonteUsuario: "Valor informado pelo usuário (fabricante ou critério próprio).",
    semMta: "Sem MTA definida.",
    comandoCopiado: "Comando copiado.",
  },
  celular: {
    // página que abre no celular
    aoVivo: "Ao vivo",
    pronto: "Pronto",
    analisando: "Analisando",
    fotoAnalisada: "Foto analisada",
    pausado: "Pausado",
    pausar: "Pausar",
    continuar: "Continuar",
    semConexao: "Sem conexão com o Pyron. Confira se o celular está no mesmo Wi-Fi do computador.",
    semModelo: "Sem modelo",
    erroServidor: (s) => `O Pyron respondeu com erro ${s}.`,
    semCameraAoVivo: "Este navegador não liberou a câmera ao vivo. Tire uma foto para analisar.",
    cameraNegada: "A câmera foi bloqueada. Toque no ícone ao lado do endereço › Permissões › Câmera › Permitir e recarregue a página.",
    cameraFalhou: (m) => `Não consegui abrir a câmera${m ? `: ${m}` : "."}`,
    nadaAchado: "Nenhum componente confirmado ainda. Segure firme e enquadre a imagem inteira.",
    procurando: "Procurando a imagem térmica: aproxime até ela ocupar boa parte da tela.",
    procurandoCurto: "Procurando",
    rotulo: (nome, pct) => `${nome} ${pct}%`,
    confianca: (pct) => `${pct}%`,
    ritmo: (v) => `${v}/s`,
    zoom: (z) => `${z}×`,
    zoomFalhou: "Esta câmera não aceitou o zoom.",
    semQuadro: "A câmera ainda não mandou imagem.",
    salvando: "Salvando no Pyron…",
    salvo: (n) => `Salvo no Pyron com ${n} ${n === 1 ? "componente" : "componentes"}.`,
    // tela Câmera do celular, no computador
    erroTitulo: "Não consegui ver o modo celular",
    comoTitulo: "Conectar o celular",
    passos: [
      "Deixe o celular e o computador no mesmo Wi-Fi.",
      "Ligue a conexão aqui e leia o QR code com a câmera do celular.",
      "O celular vai avisar que a conexão não é particular: toque em Avançado › Continuar. O certificado é do próprio Pyron.",
      "Permita a câmera e aponte para a imagem térmica.",
    ],
    ligar: "Ligar conexão com o celular",
    modeloUsado: (nome) => `Modelo usado: ${nome}. Só identificação: a foto do celular não traz temperatura.`,
    notaRede: "O Windows pode perguntar se o Pyron pode usar a rede: permita em redes privadas. A conexão fica só na sua rede, com um código no link, e desliga quando você desligar aqui ou fechar o Pyron.",
    abraTitulo: "Abra no celular",
    qrAlt: "QR code com o endereço do Pyron para o celular",
    copiar: "Copiar",
    avisoCertificado: "No aviso de conexão não particular, toque em Avançado › Continuar.",
    desligar: "Desligar",
    desligado: "Conexão com o celular desligada.",
    espelhoTitulo: "O que o celular está vendo",
    espelhoAlt: "Último quadro recebido do celular, com os componentes marcados",
    esperandoTitulo: "Esperando o celular",
    esperandoTexto: "Abra o endereço no celular e ligue a câmera. Os quadros aparecem aqui.",
    conectado: "Celular conectado",
    esperando: "Esperando o celular abrir a página",
    desconectado: (s) => `Sem quadros há ${s} s: o celular saiu da página ou perdeu o Wi-Fi`,
    ritmoPc: (v, ms) => `${v} análises/s · detector ${ms} ms`,
    nenhumNoQuadro: "Nenhum componente confirmado no último quadro.",
    semTermograma: "Nenhuma imagem térmica no último quadro.",
    capturas: (n) => `${n} ${n === 1 ? "captura salva" : "capturas salvas"}`,
    verInspecoes: "Ver em Inspeções",
    naoConectou: "Se o celular não abrir a página: confira o Wi-Fi dos dois e se o Windows liberou o Pyron no firewall para redes privadas.",
  },
};
